import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import withWebLayout from '../layout/webLayout/withWebLayout'
import HomeModule from '@/components/homeModule/homeModule'


const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeModule />
    </>
  )
}

export default withWebLayout(Home);
